Update pullrequest.yml

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -26,10 +26,10 @@ jobs:
     - name: "[Pre] Install Docker"
       shell: bash
       run: |
-          brew install docker docker-machine-driver-hyperkit
-          sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-hyperkit/bin/docker-machine-driver-hyperkit
-          sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-hyperkit/bin/docker-machine-driver-hyperkit
-          while ! docker-machine create --driver hyperkit default; do
+          brew install docker docker-machine-driver-generic
+          sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-generic/bin/docker-machine-driver-generic
+          sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-v/bin/docker-machine-driver-generic
+          while ! docker-machine create --driver generic default; do
             docker-machine rm -f default
             sleep 1;
           done
@@ -109,6 +109,6 @@ jobs:
     - name: Run Integration Tests - iOS
       run: mono /Users/runner/runners/2.163.1/work/MobileApplication/MobileApplication/TransactionMobile/packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe TransactionMobile/TransactionMobile.IntegrationTests/bin/Release/TransactionMobile.IntegrationTests.dll --where "cat == iOS"
     
-    - name: Setup tmate session
-      if: failure()
-      uses: mxschmitt/action-tmate@v1
+    #- name: Setup tmate session
+      #if: failure()
+      #uses: mxschmitt/action-tmate@v1
